# volumes:
services:
  profile:
    build:
        context: profile
        dockerfile: Dockerfile.dev
    ports:
        - "8100:8000"
    volumes:
        - ./profile:/app
    environment:
      DATABASE_URL: postgresql://profile:password@postgres/profile
      WAIT_HOSTS: postgres:5432
      SIGNING_KEY: 8461fadcd908ae362d80be6da7314c020633c57e2082d619a5b56443e0ae9e6baa418a873078547828d81e485909e93c22b4482139192fd9ad72d7b2c7e3ba7a
  
  messaging:
    build:
        context: messaging
        dockerfile: Dockerfile.dev
    ports:
        - "8200:8000"
    volumes:
        - ./messaging:/app
    environment:
      DATABASE_URL: postgresql://messaging:password@postgres/messaging
      WAIT_HOSTS: postgres:5432
  
  notifactions:
    build:
        context: notifications
        dockerfile: Dockerfile.dev
    ports:
        - "8300:8000"
    volumes:
        - ./notifications:/app
    environment:
      DATABASE_URL: postgresql://notifications:password@postgres/notifications
      WAIT_HOSTS: postgres:5432
  
  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      REACT_APP_API_HOST: http://localhost:8000

  postgres:
        build:
            context: relational-data
            dockerfile: Dockerfile.dev
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_MULTIPLE_DATABASES= profile, messaging, notifactions
            - POSTGRES_PASSWORD=password
        ports:
            - 15432:5432
  pg-admin:
    image: dpage/pgadmin4
    volumes:
      - pg-admin:/var/lib/pgadmin
    ports:
      - 8082:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pawwow@email.com
      PGADMIN_DEFAULT_PASSWORD: pawwow
      PGADMIN_DISABLE_POSTFIX: 1
volumes:
  postgres-data:
      external: true
  pg-admin:
      external: true


